// Code generated by protoc-gen-go.
// source: github.com/micro/organization-srv/proto/org/org.proto
// DO NOT EDIT!

/*
Package org is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/organization-srv/proto/org/org.proto

It has these top-level messages:
	Organization
	Member
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
	CreateMemberRequest
	CreateMemberResponse
	DeleteMemberRequest
	DeleteMemberResponse
	ReadMemberRequest
	ReadMemberResponse
	UpdateMemberRequest
	UpdateMemberResponse
	SearchMembersRequest
	SearchMembersResponse
*/
package org

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Organization struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	Created int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated int64  `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Member struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgName  string   `protobuf:"bytes,2,opt,name=orgName" json:"orgName,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Roles    []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
	Created  int64    `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated  int64    `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ReadResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SearchResponse struct {
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type CreateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *CreateMemberRequest) Reset()                    { *m = CreateMemberRequest{} }
func (m *CreateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberRequest) ProtoMessage()               {}
func (*CreateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateMemberResponse struct {
}

func (m *CreateMemberResponse) Reset()                    { *m = CreateMemberResponse{} }
func (m *CreateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberResponse) ProtoMessage()               {}
func (*CreateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type DeleteMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteMemberRequest) Reset()                    { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()               {}
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type DeleteMemberResponse struct {
}

func (m *DeleteMemberResponse) Reset()                    { *m = DeleteMemberResponse{} }
func (m *DeleteMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberResponse) ProtoMessage()               {}
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ReadMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadMemberRequest) Reset()                    { *m = ReadMemberRequest{} }
func (m *ReadMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberRequest) ProtoMessage()               {}
func (*ReadMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ReadMemberResponse struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *ReadMemberResponse) Reset()                    { *m = ReadMemberResponse{} }
func (m *ReadMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberResponse) ProtoMessage()               {}
func (*ReadMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ReadMemberResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *UpdateMemberRequest) Reset()                    { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()               {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberResponse struct {
}

func (m *UpdateMemberResponse) Reset()                    { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()               {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type SearchMembersRequest struct {
	OrgName  string `protobuf:"bytes,1,opt,name=orgName" json:"orgName,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchMembersRequest) Reset()                    { *m = SearchMembersRequest{} }
func (m *SearchMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersRequest) ProtoMessage()               {}
func (*SearchMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type SearchMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *SearchMembersResponse) Reset()                    { *m = SearchMembersResponse{} }
func (m *SearchMembersResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersResponse) ProtoMessage()               {}
func (*SearchMembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SearchMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "Organization")
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*CreateMemberRequest)(nil), "CreateMemberRequest")
	proto.RegisterType((*CreateMemberResponse)(nil), "CreateMemberResponse")
	proto.RegisterType((*DeleteMemberRequest)(nil), "DeleteMemberRequest")
	proto.RegisterType((*DeleteMemberResponse)(nil), "DeleteMemberResponse")
	proto.RegisterType((*ReadMemberRequest)(nil), "ReadMemberRequest")
	proto.RegisterType((*ReadMemberResponse)(nil), "ReadMemberResponse")
	proto.RegisterType((*UpdateMemberRequest)(nil), "UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "UpdateMemberResponse")
	proto.RegisterType((*SearchMembersRequest)(nil), "SearchMembersRequest")
	proto.RegisterType((*SearchMembersResponse)(nil), "SearchMembersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Org service

type OrgClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...client.CallOption) (*CreateMemberResponse, error)
	ReadMember(ctx context.Context, in *ReadMemberRequest, opts ...client.CallOption) (*ReadMemberResponse, error)
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...client.CallOption) (*DeleteMemberResponse, error)
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...client.CallOption) (*UpdateMemberResponse, error)
	SearchMembers(ctx context.Context, in *SearchMembersRequest, opts ...client.CallOption) (*SearchMembersResponse, error)
}

type orgClient struct {
	c           client.Client
	serviceName string
}

func NewOrgClient(serviceName string, c client.Client) OrgClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "org"
	}
	return &orgClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *orgClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...client.CallOption) (*CreateMemberResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.CreateMember", in)
	out := new(CreateMemberResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) ReadMember(ctx context.Context, in *ReadMemberRequest, opts ...client.CallOption) (*ReadMemberResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.ReadMember", in)
	out := new(ReadMemberResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...client.CallOption) (*DeleteMemberResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.DeleteMember", in)
	out := new(DeleteMemberResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...client.CallOption) (*UpdateMemberResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.UpdateMember", in)
	out := new(UpdateMemberResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) SearchMembers(ctx context.Context, in *SearchMembersRequest, opts ...client.CallOption) (*SearchMembersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Org.SearchMembers", in)
	out := new(SearchMembersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Org service

type OrgHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	CreateMember(context.Context, *CreateMemberRequest, *CreateMemberResponse) error
	ReadMember(context.Context, *ReadMemberRequest, *ReadMemberResponse) error
	DeleteMember(context.Context, *DeleteMemberRequest, *DeleteMemberResponse) error
	UpdateMember(context.Context, *UpdateMemberRequest, *UpdateMemberResponse) error
	SearchMembers(context.Context, *SearchMembersRequest, *SearchMembersResponse) error
}

func RegisterOrgHandler(s server.Server, hdlr OrgHandler) {
	s.Handle(s.NewHandler(&Org{hdlr}))
}

type Org struct {
	OrgHandler
}

func (h *Org) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.OrgHandler.Create(ctx, in, out)
}

func (h *Org) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.OrgHandler.Read(ctx, in, out)
}

func (h *Org) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.OrgHandler.Delete(ctx, in, out)
}

func (h *Org) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.OrgHandler.Update(ctx, in, out)
}

func (h *Org) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.OrgHandler.Search(ctx, in, out)
}

func (h *Org) CreateMember(ctx context.Context, in *CreateMemberRequest, out *CreateMemberResponse) error {
	return h.OrgHandler.CreateMember(ctx, in, out)
}

func (h *Org) ReadMember(ctx context.Context, in *ReadMemberRequest, out *ReadMemberResponse) error {
	return h.OrgHandler.ReadMember(ctx, in, out)
}

func (h *Org) DeleteMember(ctx context.Context, in *DeleteMemberRequest, out *DeleteMemberResponse) error {
	return h.OrgHandler.DeleteMember(ctx, in, out)
}

func (h *Org) UpdateMember(ctx context.Context, in *UpdateMemberRequest, out *UpdateMemberResponse) error {
	return h.OrgHandler.UpdateMember(ctx, in, out)
}

func (h *Org) SearchMembers(ctx context.Context, in *SearchMembersRequest, out *SearchMembersResponse) error {
	return h.OrgHandler.SearchMembers(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x4d, 0xea, 0xd4, 0xf9, 0xfd, 0xa6, 0x76, 0x5a, 0x36, 0x49, 0x31, 0xe6, 0x00, 0x18, 0x90,
	0x90, 0x50, 0x37, 0xa2, 0xe5, 0xcf, 0x09, 0x09, 0x09, 0x6e, 0x08, 0x90, 0x8a, 0x90, 0xb8, 0x3a,
	0xc9, 0xb6, 0xb1, 0x14, 0xdb, 0x61, 0xd7, 0x01, 0x89, 0x4f, 0xc2, 0xc7, 0x65, 0xbc, 0x7f, 0x9a,
	0xdd, 0x64, 0x2b, 0x85, 0x43, 0x0f, 0x3b, 0x7e, 0x33, 0xf3, 0xde, 0xcc, 0x9b, 0x06, 0x5e, 0x5d,
	0x17, 0xcd, 0x62, 0x3d, 0xa5, 0xb3, 0xba, 0x9c, 0x94, 0xc5, 0x8c, 0xd7, 0x93, 0x9a, 0x5f, 0xe7,
	0x55, 0xf1, 0x3b, 0x6f, 0x8a, 0xba, 0x3a, 0x13, 0xfc, 0xe7, 0x64, 0xc5, 0xeb, 0x46, 0x86, 0xdb,
	0x3f, 0x2a, 0x5f, 0xd9, 0x02, 0xa2, 0x2f, 0x16, 0x8e, 0x00, 0x1c, 0x14, 0xf3, 0xa4, 0xfb, 0xb0,
	0xfb, 0xec, 0x7f, 0x12, 0x41, 0xaf, 0xca, 0x4b, 0x96, 0x1c, 0xc8, 0x57, 0x0c, 0x87, 0xac, 0xcc,
	0x8b, 0x65, 0x12, 0x98, 0x67, 0xfd, 0xab, 0x62, 0x3c, 0xe9, 0xc9, 0xe7, 0x31, 0xf4, 0x67, 0x9c,
	0xe5, 0x0d, 0x9b, 0x27, 0x87, 0x18, 0x08, 0xda, 0xc0, 0x7a, 0x35, 0x97, 0x81, 0xb0, 0x0d, 0x60,
	0xa7, 0xf0, 0x13, 0x2b, 0xa7, 0x8c, 0x3b, 0x3d, 0x10, 0x86, 0x64, 0x3e, 0x6f, 0xda, 0x9c, 0xc0,
	0x7f, 0x6b, 0xc1, 0xb8, 0x6c, 0x7c, 0xd3, 0x89, 0xd7, 0x4b, 0x26, 0xb0, 0x53, 0xb0, 0x57, 0xa7,
	0x97, 0x10, 0xbf, 0x97, 0x88, 0x4b, 0xf6, 0x63, 0xcd, 0x44, 0x43, 0x1e, 0x43, 0x64, 0x0f, 0x43,
	0xb6, 0x3e, 0x3a, 0x8f, 0xa9, 0xad, 0x3c, 0x3b, 0x81, 0x81, 0xc9, 0x12, 0xab, 0xba, 0x12, 0x2c,
	0xbb, 0x0f, 0xf1, 0x07, 0xb6, 0x64, 0x9b, 0x3a, 0x16, 0xf1, 0x16, 0x6e, 0x3e, 0x6a, 0xf8, 0x3d,
	0x38, 0xba, 0x64, 0xf9, 0xdc, 0x07, 0xbe, 0x80, 0x48, 0x7d, 0x52, 0xd0, 0xfd, 0x08, 0xa1, 0x8c,
	0x6f, 0x52, 0xd7, 0xbf, 0xca, 0x30, 0x59, 0x9a, 0xd7, 0x47, 0x88, 0xbf, 0xb2, 0x9c, 0xcf, 0x16,
	0xa6, 0x8e, 0xd9, 0x6b, 0xd7, 0x5d, 0xe4, 0xcd, 0x9a, 0x97, 0x45, 0x59, 0x34, 0x72, 0xf8, 0x01,
	0x19, 0x40, 0x58, 0x5f, 0x5d, 0x09, 0xd6, 0xc8, 0x3d, 0x07, 0xd9, 0x6b, 0x18, 0x98, 0x62, 0x5a,
	0xcb, 0x13, 0x88, 0x6d, 0x56, 0x02, 0xcb, 0x06, 0xbb, 0xb4, 0x28, 0x0c, 0xd5, 0x74, 0x95, 0x07,
	0x0c, 0x95, 0xbb, 0x10, 0x96, 0x32, 0xa0, 0xc5, 0xf4, 0xa9, 0xfa, 0x9e, 0x9d, 0xc2, 0xc8, 0xc5,
	0x6b, 0x31, 0x8f, 0x60, 0xa8, 0xc6, 0xee, 0xd6, 0xb1, 0x87, 0x8d, 0xa9, 0x2e, 0x44, 0xa7, 0x3e,
	0x80, 0x3b, 0xed, 0x12, 0x6e, 0x4f, 0x3c, 0x03, 0x62, 0x03, 0xb4, 0xbe, 0x5b, 0x29, 0xa2, 0x24,
	0x35, 0xe9, 0xfd, 0x25, 0xb9, 0x78, 0xcd, 0xeb, 0x3b, 0x8c, 0xd4, 0x48, 0x55, 0x5c, 0x98, 0x42,
	0xd6, 0x69, 0x74, 0x77, 0x4e, 0x63, 0xaf, 0x65, 0xbd, 0x80, 0xf1, 0x56, 0x65, 0xad, 0x29, 0x81,
	0xbe, 0xe2, 0x68, 0xb6, 0x65, 0x48, 0x9e, 0xff, 0xe9, 0x41, 0x80, 0x8b, 0x23, 0xcf, 0x21, 0x54,
	0xf3, 0x27, 0x03, 0xea, 0x1c, 0x53, 0x7a, 0x4c, 0xb7, 0xce, 0xa4, 0x43, 0x9e, 0x42, 0xaf, 0x1d,
	0x1c, 0x89, 0xa8, 0x75, 0x00, 0x69, 0x4c, 0x6d, 0xcf, 0x23, 0x0c, 0x6b, 0xaa, 0xc5, 0x60, 0x4d,
	0xe7, 0xb0, 0xb0, 0xe6, 0xd6, 0x2d, 0x49, 0xb0, 0x9a, 0x16, 0x82, 0x9d, 0x33, 0x40, 0xf0, 0x96,
	0xc1, 0x25, 0x58, 0x09, 0x45, 0xb0, 0xe3, 0x75, 0x04, 0xbb, 0x76, 0x45, 0xf0, 0x5b, 0x88, 0x6c,
	0x6b, 0x91, 0x11, 0xf5, 0x38, 0x33, 0x1d, 0x53, 0xaf, 0xff, 0x3a, 0xe4, 0x0d, 0xc0, 0xc6, 0x25,
	0x84, 0xd0, 0x1d, 0x4f, 0xa5, 0x43, 0xba, 0x6b, 0x23, 0xd5, 0xd7, 0xf6, 0x25, 0xf6, 0xf5, 0x38,
	0x19, 0xfb, 0x7a, 0xcd, 0x2b, 0xd3, 0x6d, 0xfb, 0x60, 0xba, 0xc7, 0x7d, 0x98, 0xee, 0xf5, 0x58,
	0x87, 0xbc, 0x33, 0xff, 0x05, 0xb4, 0x17, 0xc8, 0x98, 0xfa, 0x5c, 0x97, 0x9e, 0x52, 0xaf, 0x65,
	0xb2, 0xce, 0x34, 0x94, 0xbf, 0x18, 0x17, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xdd, 0x7d,
	0x2b, 0x6a, 0x06, 0x00, 0x00,
}
