// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/organization-srv/proto/org/org.proto

/*
Package org is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/organization-srv/proto/org/org.proto

It has these top-level messages:
	Organization
	Member
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
	CreateMemberRequest
	CreateMemberResponse
	DeleteMemberRequest
	DeleteMemberResponse
	ReadMemberRequest
	ReadMemberResponse
	UpdateMemberRequest
	UpdateMemberResponse
	SearchMembersRequest
	SearchMembersResponse
*/
package org

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organization struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	Created int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated int64  `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Organization) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Organization) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Organization) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Organization) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Member struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgName  string   `protobuf:"bytes,2,opt,name=orgName" json:"orgName,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Roles    []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
	Created  int64    `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated  int64    `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *Member) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Member) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Member) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Member) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type CreateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *CreateMemberRequest) Reset()                    { *m = CreateMemberRequest{} }
func (m *CreateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberRequest) ProtoMessage()               {}
func (*CreateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateMemberResponse struct {
}

func (m *CreateMemberResponse) Reset()                    { *m = CreateMemberResponse{} }
func (m *CreateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberResponse) ProtoMessage()               {}
func (*CreateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type DeleteMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteMemberRequest) Reset()                    { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()               {}
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeleteMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMemberResponse struct {
}

func (m *DeleteMemberResponse) Reset()                    { *m = DeleteMemberResponse{} }
func (m *DeleteMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberResponse) ProtoMessage()               {}
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ReadMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadMemberRequest) Reset()                    { *m = ReadMemberRequest{} }
func (m *ReadMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberRequest) ProtoMessage()               {}
func (*ReadMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ReadMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadMemberResponse struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *ReadMemberResponse) Reset()                    { *m = ReadMemberResponse{} }
func (m *ReadMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberResponse) ProtoMessage()               {}
func (*ReadMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ReadMemberResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *UpdateMemberRequest) Reset()                    { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()               {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberResponse struct {
}

func (m *UpdateMemberResponse) Reset()                    { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()               {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type SearchMembersRequest struct {
	OrgName  string `protobuf:"bytes,1,opt,name=orgName" json:"orgName,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchMembersRequest) Reset()                    { *m = SearchMembersRequest{} }
func (m *SearchMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersRequest) ProtoMessage()               {}
func (*SearchMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *SearchMembersRequest) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *SearchMembersRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SearchMembersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchMembersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *SearchMembersResponse) Reset()                    { *m = SearchMembersResponse{} }
func (m *SearchMembersResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersResponse) ProtoMessage()               {}
func (*SearchMembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SearchMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "Organization")
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*CreateMemberRequest)(nil), "CreateMemberRequest")
	proto.RegisterType((*CreateMemberResponse)(nil), "CreateMemberResponse")
	proto.RegisterType((*DeleteMemberRequest)(nil), "DeleteMemberRequest")
	proto.RegisterType((*DeleteMemberResponse)(nil), "DeleteMemberResponse")
	proto.RegisterType((*ReadMemberRequest)(nil), "ReadMemberRequest")
	proto.RegisterType((*ReadMemberResponse)(nil), "ReadMemberResponse")
	proto.RegisterType((*UpdateMemberRequest)(nil), "UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "UpdateMemberResponse")
	proto.RegisterType((*SearchMembersRequest)(nil), "SearchMembersRequest")
	proto.RegisterType((*SearchMembersResponse)(nil), "SearchMembersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Org service

type OrgClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*CreateMemberResponse, error)
	ReadMember(ctx context.Context, in *ReadMemberRequest, opts ...grpc.CallOption) (*ReadMemberResponse, error)
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*DeleteMemberResponse, error)
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*UpdateMemberResponse, error)
	SearchMembers(ctx context.Context, in *SearchMembersRequest, opts ...grpc.CallOption) (*SearchMembersResponse, error)
}

type orgClient struct {
	cc *grpc.ClientConn
}

func NewOrgClient(cc *grpc.ClientConn) OrgClient {
	return &orgClient{cc}
}

func (c *orgClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/Org/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/Org/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/Org/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/Org/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/Org/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) CreateMember(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*CreateMemberResponse, error) {
	out := new(CreateMemberResponse)
	err := grpc.Invoke(ctx, "/Org/CreateMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) ReadMember(ctx context.Context, in *ReadMemberRequest, opts ...grpc.CallOption) (*ReadMemberResponse, error) {
	out := new(ReadMemberResponse)
	err := grpc.Invoke(ctx, "/Org/ReadMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*DeleteMemberResponse, error) {
	out := new(DeleteMemberResponse)
	err := grpc.Invoke(ctx, "/Org/DeleteMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*UpdateMemberResponse, error) {
	out := new(UpdateMemberResponse)
	err := grpc.Invoke(ctx, "/Org/UpdateMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) SearchMembers(ctx context.Context, in *SearchMembersRequest, opts ...grpc.CallOption) (*SearchMembersResponse, error) {
	out := new(SearchMembersResponse)
	err := grpc.Invoke(ctx, "/Org/SearchMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Org service

type OrgServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	CreateMember(context.Context, *CreateMemberRequest) (*CreateMemberResponse, error)
	ReadMember(context.Context, *ReadMemberRequest) (*ReadMemberResponse, error)
	DeleteMember(context.Context, *DeleteMemberRequest) (*DeleteMemberResponse, error)
	UpdateMember(context.Context, *UpdateMemberRequest) (*UpdateMemberResponse, error)
	SearchMembers(context.Context, *SearchMembersRequest) (*SearchMembersResponse, error)
}

func RegisterOrgServer(s *grpc.Server, srv OrgServer) {
	s.RegisterService(&_Org_serviceDesc, srv)
}

func _Org_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_CreateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).CreateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/CreateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).CreateMember(ctx, req.(*CreateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_ReadMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).ReadMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/ReadMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).ReadMember(ctx, req.(*ReadMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).DeleteMember(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/UpdateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).UpdateMember(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_SearchMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).SearchMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Org/SearchMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).SearchMembers(ctx, req.(*SearchMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Org_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Org",
	HandlerType: (*OrgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Org_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Org_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Org_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Org_Update_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Org_Search_Handler,
		},
		{
			MethodName: "CreateMember",
			Handler:    _Org_CreateMember_Handler,
		},
		{
			MethodName: "ReadMember",
			Handler:    _Org_ReadMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _Org_DeleteMember_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _Org_UpdateMember_Handler,
		},
		{
			MethodName: "SearchMembers",
			Handler:    _Org_SearchMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/micro/organization-srv/proto/org/org.proto",
}

func init() {
	proto.RegisterFile("github.com/micro/organization-srv/proto/org/org.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x6d, 0x6b, 0xd3, 0x50,
	0x14, 0x6e, 0x9a, 0xae, 0xd5, 0xb3, 0x26, 0xd5, 0xd3, 0xb4, 0x84, 0x80, 0xac, 0x46, 0x06, 0x03,
	0xf1, 0x0c, 0x37, 0x36, 0x41, 0x10, 0x74, 0xea, 0x47, 0x1d, 0x44, 0xfc, 0x01, 0x59, 0x7b, 0xd7,
	0x05, 0x9a, 0x66, 0xde, 0xa4, 0x0a, 0xfb, 0x19, 0x7e, 0xda, 0xcf, 0x95, 0xdc, 0x97, 0xed, 0xde,
	0x36, 0x53, 0x36, 0x3f, 0x14, 0x7a, 0x5e, 0xef, 0x73, 0xce, 0x79, 0x9e, 0x16, 0x8e, 0xe6, 0x59,
	0x75, 0xb1, 0x3a, 0xa3, 0x69, 0x91, 0xef, 0xe7, 0xd9, 0x94, 0x17, 0xfb, 0x05, 0x9f, 0xa7, 0xcb,
	0xec, 0x2a, 0xad, 0xb2, 0x62, 0xf9, 0xaa, 0xe4, 0x3f, 0xf7, 0x2f, 0x79, 0x51, 0x09, 0x77, 0xfd,
	0x21, 0x61, 0xc5, 0xbf, 0x1d, 0xe8, 0x9f, 0x1a, 0x89, 0xe8, 0x43, 0x3b, 0x9b, 0x85, 0xce, 0xc4,
	0xd9, 0x7b, 0x9c, 0xb4, 0xb3, 0x19, 0x22, 0x74, 0x96, 0x69, 0xce, 0xc2, 0xb6, 0xf0, 0x88, 0xef,
	0x18, 0xc0, 0x16, 0xcb, 0xd3, 0x6c, 0x11, 0xba, 0xc2, 0x29, 0x8d, 0xda, 0x5b, 0xfc, 0x5a, 0x32,
	0x1e, 0x76, 0xa4, 0x57, 0x18, 0x18, 0x42, 0x6f, 0xca, 0x59, 0x5a, 0xb1, 0x59, 0xb8, 0x35, 0x71,
	0xf6, 0xdc, 0x44, 0x9b, 0x75, 0x64, 0x75, 0x39, 0x13, 0x91, 0xae, 0x8c, 0x28, 0x33, 0xbe, 0x76,
	0xa0, 0xfb, 0x85, 0xe5, 0x67, 0x8c, 0x6f, 0xc0, 0x09, 0xa1, 0x57, 0xf0, 0xf9, 0xd7, 0x5b, 0x44,
	0xda, 0xc4, 0x08, 0x1e, 0xad, 0x4a, 0xc6, 0x05, 0x58, 0x89, 0xeb, 0xc6, 0xae, 0xa1, 0xf1, 0x62,
	0xc1, 0xca, 0xb0, 0x33, 0x71, 0x6b, 0x68, 0xc2, 0x78, 0x10, 0xb4, 0x13, 0xf0, 0x3e, 0x8a, 0xa4,
	0x84, 0xfd, 0x58, 0xb1, 0xb2, 0xc2, 0xd7, 0xd0, 0x37, 0x17, 0x2d, 0xa0, 0x6e, 0x1f, 0x78, 0x64,
	0x2e, 0x35, 0xb1, 0x52, 0xe2, 0x27, 0xe0, 0xeb, 0x1e, 0xe5, 0x65, 0xb1, 0x2c, 0x59, 0xbc, 0x03,
	0xde, 0x27, 0xb6, 0x60, 0xb7, 0x5d, 0xd7, 0xc6, 0xae, 0x4b, 0x74, 0x82, 0x2a, 0x79, 0x06, 0xdb,
	0x09, 0x4b, 0x67, 0x77, 0x15, 0x7c, 0x80, 0xbe, 0x0c, 0xcb, 0xf4, 0x87, 0xc0, 0x3c, 0x01, 0xef,
	0xbb, 0x98, 0xfa, 0xff, 0x46, 0xd5, 0x3d, 0x14, 0xee, 0x39, 0x78, 0xdf, 0x58, 0xca, 0xa7, 0x17,
	0xba, 0xab, 0x26, 0x98, 0x63, 0x13, 0x4c, 0x52, 0xa9, 0x6d, 0x52, 0x29, 0x80, 0xad, 0x45, 0x96,
	0x67, 0x95, 0x38, 0xaf, 0x9b, 0x48, 0x03, 0xc7, 0xd0, 0x2d, 0xce, 0xcf, 0x4b, 0x56, 0x09, 0xde,
	0xb9, 0x89, 0xb2, 0xe2, 0xcf, 0xe0, 0xeb, 0x87, 0xd4, 0x0e, 0x0e, 0xc1, 0x33, 0xc1, 0x95, 0xa1,
	0x33, 0x71, 0x37, 0x07, 0xb0, 0x73, 0xe2, 0x63, 0x18, 0xca, 0x63, 0x49, 0x42, 0x6a, 0xd4, 0x3b,
	0xd0, 0xcd, 0x85, 0x43, 0x6d, 0xa1, 0x47, 0x2a, 0xae, 0xdc, 0xf1, 0x18, 0x02, 0xbb, 0x4e, 0xcd,
	0xbf, 0x0b, 0x43, 0x79, 0x49, 0xbb, 0xdf, 0xfa, 0xfd, 0xc6, 0x10, 0xd8, 0x69, 0xaa, 0xfc, 0x05,
	0x3c, 0xad, 0xef, 0xfa, 0xf7, 0xe2, 0x23, 0x40, 0x33, 0x49, 0x8d, 0xff, 0x4f, 0xc8, 0xc7, 0x30,
	0x94, 0xc7, 0xba, 0xff, 0xa8, 0x76, 0x9d, 0xc2, 0x7a, 0x05, 0x81, 0xbc, 0x80, 0xf4, 0x97, 0xba,
	0xa1, 0xa1, 0x61, 0xe7, 0x6e, 0x0d, 0xb7, 0x37, 0x35, 0x7c, 0x8f, 0xeb, 0xbf, 0x85, 0xd1, 0xda,
	0xdb, 0x6a, 0x0b, 0xcf, 0xa1, 0x27, 0x61, 0xeb, 0xf3, 0xdf, 0x8c, 0xa3, 0xfd, 0x07, 0xd7, 0x1d,
	0x70, 0x4f, 0xf9, 0x1c, 0x5f, 0x42, 0x57, 0x9e, 0x10, 0x7d, 0xb2, 0x44, 0x1f, 0x0d, 0x68, 0x4d,
	0xc0, 0x2d, 0xdc, 0x85, 0x4e, 0xbd, 0x73, 0xec, 0x93, 0x21, 0xcb, 0xc8, 0x23, 0x53, 0x85, 0x71,
	0xab, 0xee, 0x29, 0xef, 0x8a, 0x3e, 0x59, 0x92, 0x8f, 0x06, 0xb4, 0xa6, 0x70, 0x91, 0x2c, 0x17,
	0x8b, 0x3e, 0x59, 0x52, 0x8c, 0x06, 0xb4, 0x26, 0x2b, 0x91, 0x2c, 0x27, 0x46, 0x9f, 0x2c, 0x85,
	0x45, 0x03, 0xb2, 0x85, 0x10, 0xb7, 0xf0, 0x1d, 0xf4, 0x4d, 0x76, 0x62, 0x40, 0x0d, 0x24, 0x8f,
	0x46, 0xd4, 0x48, 0xe1, 0x16, 0xbe, 0x01, 0xb8, 0x25, 0x18, 0x22, 0x6d, 0x50, 0x32, 0x1a, 0xd2,
	0x26, 0x03, 0xe5, 0xbb, 0x26, 0xad, 0x31, 0xa0, 0x06, 0x31, 0x44, 0x23, 0x6a, 0xe4, 0xbe, 0x28,
	0x37, 0x99, 0x86, 0x01, 0x35, 0x10, 0x36, 0x1a, 0x51, 0x23, 0x1d, 0x5b, 0xf8, 0x5e, 0xff, 0xf6,
	0x28, 0x52, 0xe0, 0x88, 0x9a, 0x08, 0x1a, 0x8d, 0xa9, 0x91, 0x3b, 0x71, 0xeb, 0xac, 0x2b, 0xfe,
	0x35, 0x0f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x11, 0x02, 0xa7, 0x08, 0x6e, 0x07, 0x00, 0x00,
}
