// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/organization-srv/proto/org/org.proto

/*
Package org is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/organization-srv/proto/org/org.proto

It has these top-level messages:
	Organization
	Member
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
	CreateMemberRequest
	CreateMemberResponse
	DeleteMemberRequest
	DeleteMemberResponse
	ReadMemberRequest
	ReadMemberResponse
	UpdateMemberRequest
	UpdateMemberResponse
	SearchMembersRequest
	SearchMembersResponse
*/
package org

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organization struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	Created int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated int64  `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Organization) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Organization) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Organization) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Organization) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Member struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgName  string   `protobuf:"bytes,2,opt,name=orgName" json:"orgName,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Roles    []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
	Created  int64    `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Updated  int64    `protobuf:"varint,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *Member) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Member) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Member) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Member) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type CreateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *CreateMemberRequest) Reset()                    { *m = CreateMemberRequest{} }
func (m *CreateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberRequest) ProtoMessage()               {}
func (*CreateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateMemberResponse struct {
}

func (m *CreateMemberResponse) Reset()                    { *m = CreateMemberResponse{} }
func (m *CreateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMemberResponse) ProtoMessage()               {}
func (*CreateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type DeleteMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteMemberRequest) Reset()                    { *m = DeleteMemberRequest{} }
func (m *DeleteMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberRequest) ProtoMessage()               {}
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeleteMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMemberResponse struct {
}

func (m *DeleteMemberResponse) Reset()                    { *m = DeleteMemberResponse{} }
func (m *DeleteMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteMemberResponse) ProtoMessage()               {}
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ReadMemberRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadMemberRequest) Reset()                    { *m = ReadMemberRequest{} }
func (m *ReadMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberRequest) ProtoMessage()               {}
func (*ReadMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ReadMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadMemberResponse struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *ReadMemberResponse) Reset()                    { *m = ReadMemberResponse{} }
func (m *ReadMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadMemberResponse) ProtoMessage()               {}
func (*ReadMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ReadMemberResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *UpdateMemberRequest) Reset()                    { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()               {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type UpdateMemberResponse struct {
}

func (m *UpdateMemberResponse) Reset()                    { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()               {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type SearchMembersRequest struct {
	OrgName  string `protobuf:"bytes,1,opt,name=orgName" json:"orgName,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchMembersRequest) Reset()                    { *m = SearchMembersRequest{} }
func (m *SearchMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersRequest) ProtoMessage()               {}
func (*SearchMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *SearchMembersRequest) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *SearchMembersRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SearchMembersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchMembersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *SearchMembersResponse) Reset()                    { *m = SearchMembersResponse{} }
func (m *SearchMembersResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchMembersResponse) ProtoMessage()               {}
func (*SearchMembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SearchMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "Organization")
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*CreateMemberRequest)(nil), "CreateMemberRequest")
	proto.RegisterType((*CreateMemberResponse)(nil), "CreateMemberResponse")
	proto.RegisterType((*DeleteMemberRequest)(nil), "DeleteMemberRequest")
	proto.RegisterType((*DeleteMemberResponse)(nil), "DeleteMemberResponse")
	proto.RegisterType((*ReadMemberRequest)(nil), "ReadMemberRequest")
	proto.RegisterType((*ReadMemberResponse)(nil), "ReadMemberResponse")
	proto.RegisterType((*UpdateMemberRequest)(nil), "UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "UpdateMemberResponse")
	proto.RegisterType((*SearchMembersRequest)(nil), "SearchMembersRequest")
	proto.RegisterType((*SearchMembersResponse)(nil), "SearchMembersResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/organization-srv/proto/org/org.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x6f, 0x6b, 0xd3, 0x5e,
	0x14, 0x6e, 0x9a, 0xae, 0xfd, 0xfd, 0xce, 0x9a, 0x54, 0x4f, 0xd3, 0x12, 0x02, 0xb2, 0x1a, 0x19,
	0x0c, 0xc4, 0x33, 0xdc, 0x70, 0x03, 0x41, 0xd0, 0xa9, 0x2f, 0x75, 0x10, 0xf1, 0x03, 0x64, 0xed,
	0x5d, 0x17, 0x68, 0x9a, 0xed, 0x26, 0x55, 0xd8, 0xc7, 0xf0, 0xd5, 0x3e, 0xae, 0xe4, 0xfe, 0xd9,
	0xee, 0x6d, 0x33, 0x65, 0xf3, 0x45, 0xa1, 0xe7, 0xef, 0x7d, 0xce, 0x39, 0xcf, 0xd3, 0xc2, 0xf1,
	0x3c, 0xab, 0x2e, 0x56, 0x67, 0x34, 0x2d, 0xf2, 0xfd, 0x3c, 0x9b, 0xf2, 0xe2, 0xe2, 0x6a, 0xbf,
	0xe0, 0xf3, 0x74, 0x99, 0x5d, 0xa7, 0x55, 0x56, 0x2c, 0x5f, 0x95, 0xfc, 0xc7, 0xfe, 0x25, 0x2f,
	0xaa, 0xa2, 0x76, 0xd7, 0x1f, 0x12, 0x56, 0xfc, 0xcb, 0x81, 0xfe, 0xa9, 0x91, 0x88, 0x3e, 0xb4,
	0xb3, 0x59, 0xe8, 0x4c, 0x9c, 0xbd, 0xff, 0x93, 0x76, 0x36, 0x43, 0x84, 0xce, 0x32, 0xcd, 0x59,
	0xd8, 0x16, 0x1e, 0xf1, 0x1d, 0x03, 0xd8, 0x62, 0x79, 0x9a, 0x2d, 0x42, 0x57, 0x38, 0xa5, 0x51,
	0x7b, 0x8b, 0x9f, 0x4b, 0xc6, 0xc3, 0x8e, 0xf4, 0x0a, 0x03, 0x43, 0xe8, 0x4d, 0x39, 0x4b, 0x2b,
	0x36, 0x0b, 0xb7, 0x26, 0xce, 0x9e, 0x9b, 0x68, 0xb3, 0x8e, 0xac, 0x2e, 0x67, 0x22, 0xd2, 0x95,
	0x11, 0x65, 0xc6, 0x37, 0x0e, 0x74, 0xbf, 0xb0, 0xfc, 0x8c, 0xf1, 0x0d, 0x38, 0x21, 0xf4, 0x0a,
	0x3e, 0xff, 0x7a, 0x87, 0x48, 0x9b, 0x18, 0xc1, 0x7f, 0xab, 0x92, 0x71, 0x01, 0x56, 0xe2, 0xba,
	0xb5, 0x6b, 0x68, 0xbc, 0x58, 0xb0, 0x32, 0xec, 0x4c, 0xdc, 0x1a, 0x9a, 0x30, 0x1e, 0x05, 0xed,
	0x04, 0xbc, 0x8f, 0x22, 0x29, 0x61, 0x57, 0x2b, 0x56, 0x56, 0xf8, 0x1a, 0xfa, 0xe6, 0xa2, 0x05,
	0xd4, 0xed, 0x03, 0x8f, 0xcc, 0xa5, 0x26, 0x56, 0x4a, 0xfc, 0x04, 0x7c, 0xdd, 0xa3, 0xbc, 0x2c,
	0x96, 0x25, 0x8b, 0x77, 0xc0, 0xfb, 0xc4, 0x16, 0xec, 0xae, 0xeb, 0xda, 0xd8, 0x75, 0x89, 0x4e,
	0x50, 0x25, 0xcf, 0x60, 0x3b, 0x61, 0xe9, 0xec, 0xbe, 0x82, 0x0f, 0xd0, 0x97, 0x61, 0x99, 0xfe,
	0x18, 0x98, 0x27, 0xe0, 0x7d, 0x17, 0x53, 0xff, 0xdb, 0xa8, 0xba, 0x87, 0xc2, 0x3d, 0x07, 0xef,
	0x1b, 0x4b, 0xf9, 0xf4, 0x42, 0x77, 0xd5, 0x04, 0x73, 0x6c, 0x82, 0x49, 0x2a, 0xb5, 0x4d, 0x2a,
	0x05, 0xb0, 0xb5, 0xc8, 0xf2, 0xac, 0x12, 0xe7, 0x75, 0x13, 0x69, 0xe0, 0x18, 0xba, 0xc5, 0xf9,
	0x79, 0xc9, 0x2a, 0xc1, 0x3b, 0x37, 0x51, 0x56, 0xfc, 0x19, 0x7c, 0xfd, 0x90, 0xda, 0xc1, 0x21,
	0x78, 0x26, 0xb8, 0x32, 0x74, 0x26, 0xee, 0xe6, 0x00, 0x76, 0x4e, 0x7c, 0x04, 0x43, 0x79, 0x2c,
	0x49, 0x48, 0x8d, 0x7a, 0x07, 0xba, 0xb9, 0x70, 0xa8, 0x2d, 0xf4, 0x48, 0xc5, 0x95, 0x3b, 0x1e,
	0x43, 0x60, 0xd7, 0xa9, 0xf9, 0x77, 0x61, 0x28, 0x2f, 0x69, 0xf7, 0x5b, 0xbf, 0xdf, 0x18, 0x02,
	0x3b, 0x4d, 0x95, 0xbf, 0x80, 0xa7, 0xf5, 0x5d, 0xff, 0x5c, 0xfc, 0x06, 0xd0, 0x4c, 0x52, 0xe3,
	0xff, 0x15, 0xf2, 0x11, 0x0c, 0xe5, 0xb1, 0x1e, 0x3e, 0xaa, 0x5d, 0xa7, 0xb0, 0x5e, 0x43, 0x20,
	0x2f, 0x20, 0xfd, 0xa5, 0x6e, 0x68, 0x68, 0xd8, 0xb9, 0x5f, 0xc3, 0xed, 0x4d, 0x0d, 0x3f, 0xe0,
	0xfa, 0x6f, 0x61, 0xb4, 0xf6, 0xb6, 0xda, 0xc2, 0x73, 0xe8, 0x49, 0xd8, 0xfa, 0xfc, 0xb7, 0xe3,
	0x68, 0xff, 0xc1, 0x4d, 0x07, 0xdc, 0x53, 0x3e, 0xc7, 0x97, 0xd0, 0x95, 0x27, 0x44, 0x9f, 0x2c,
	0xd1, 0x47, 0x03, 0x5a, 0x13, 0x70, 0x0b, 0x77, 0xa1, 0x53, 0xef, 0x1c, 0xfb, 0x64, 0xc8, 0x32,
	0xf2, 0xc8, 0x54, 0x61, 0xdc, 0xaa, 0x7b, 0xca, 0xbb, 0xa2, 0x4f, 0x96, 0xe4, 0xa3, 0x01, 0xad,
	0x29, 0x5c, 0x24, 0xcb, 0xc5, 0xa2, 0x4f, 0x96, 0x14, 0xa3, 0x01, 0xad, 0xc9, 0x4a, 0x24, 0xcb,
	0x89, 0xd1, 0x27, 0x4b, 0x61, 0xd1, 0x80, 0x6c, 0x21, 0xc4, 0x2d, 0x7c, 0x07, 0x7d, 0x93, 0x9d,
	0x18, 0x50, 0x03, 0xc9, 0xa3, 0x11, 0x35, 0x52, 0xb8, 0x85, 0xc7, 0x00, 0x77, 0x04, 0x43, 0xa4,
	0x0d, 0x4a, 0x46, 0x43, 0xda, 0x64, 0xa0, 0x7c, 0xd7, 0xa4, 0x35, 0x06, 0xd4, 0x20, 0x86, 0x68,
	0x44, 0x8d, 0xdc, 0x17, 0xe5, 0x26, 0xd3, 0x30, 0xa0, 0x06, 0xc2, 0x46, 0x23, 0x6a, 0xa4, 0x63,
	0x0b, 0xdf, 0xeb, 0xdf, 0x1e, 0x45, 0x0a, 0x1c, 0x51, 0x13, 0x41, 0xa3, 0x31, 0x35, 0x72, 0x27,
	0x6e, 0x9d, 0x75, 0xc5, 0xbf, 0xe6, 0xe1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x8c, 0xa2,
	0x36, 0x70, 0x07, 0x00, 0x00,
}
